import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  UserProfile
} from '@clerk/nextjs'
import { EdgeStoreProvider } from '../lib/edgestore';
import "@/app/globals.css";
import { cn } from "@/lib/utils";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})    
import "@uploadthing/react/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
    <html lang="en">
      

      <body className={cn(
          "min-h-screen bg-background font-sans antialiased max-w-[460px] mx-auto",
          fontSans.variable
        )}>
        {/* <SignedOut>
          <SignInButton/>
        </SignedOut>
        <SignedIn>
          <UserButton/>

        </SignedIn> */}
        <EdgeStoreProvider> 
        {children}
        </EdgeStoreProvider>
        </body>
     
    </html>
    </ClerkProvider>
  );
}
